import type { Metadata } from "next"

import { Footer } from "@/components/Footer"
import { Header } from "@/components/Header"

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body style={{padding: 0, margin: 0, backgroundColor: 'lightgray'}}>
                <Header/>
                {children}
                <Footer />
            </body>
        </html>
    )
}
